language: ruby
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.1
script: bundle exec rake
before_install:
  - gem update --system
services:
  - redis-server
branches:
  except:
    - /^v[0-9]/
notifications:
  webhooks:
    urls:
      - https://lita-freenode.herokuapp.com/travis
